"""
Plain English, generated deterministically from the structured decision.

The previous view showed the machinery: `THESIS_VS_EDGE · HIGH · changes the
decision`, `Consensus STRONG_AGREEMENT`, `PRICE_HISTORY_DERIVED`, seven
confidence chips and eight honesty chips. All of it true, none of it readable,
and the thing a reader actually wants — what to do and why — was buried under
it.

This module writes the answer in the words a person would use. Two deliberate
choices:

**It is templated, not generated by a model.** A model-written summary needs an
API key, can be unavailable, and can drift from the numbers it is summarising.
This is assembled from the same object the numbers come from, so it is always
present and cannot disagree with them. The validated LLM narrative
(decision/narrative.py) remains available as a longer read on top.

**The jargon map is the whole trick.** Every internal token a reader should
never see has one plain translation, in one place. `tests/test_decision_plain.py`
enforces that the output contains no `ALL_CAPS_SNAKE` token, no `[field.path]`
citation and no `source:identifier`, which turns "make it readable" into
something a test can fail on rather than a matter of taste.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

# Where each evidence item comes from, in words. Anything not listed falls back
# to a readable form of its own name rather than leaking the identifier.
SOURCE_TEXT = {
    "pillar:technical":     "the price trend and chart indicators",
    "pillar:algo":          "the momentum models",
    "pillar:fundamentals":  "the company's reported financials",
    "pillar:research":      "analyst consensus",
    "pillar:social":        "retail chatter on Reddit and StockTwits",
    "pillar:risk":          "measured risk — volatility, beta and past drawdowns",
    "gate:statistical_edge": "the historical test of this strategy",
    "market_regime":        "the overall market environment",
    "cross_sectional_rank": "how it ranks against its peers",
    "calibration":          "this system's own track record",
    "position:cost_basis":  "your own entry price",
}

STATE_TEXT = {
    "HOLD":               "Hold what you own",
    "ADD_CONDITIONALLY":  "Adding is defensible, but only on conditions",
    "REDUCE":             "Trim the position",
    "EXIT_CONDITIONALLY": "Be ready to get out",
    "WATCH":              "Keep it on the list — nothing to do yet",
    "WAIT_FOR_ENTRY":     "Worth owning, but not at this price",
    "AVOID_NEW_POSITION": "Don't start a position here",
    "NO_TRADE":           "Nothing to do here, either way",
    "CONFLICTED":         "The evidence is split — no clear move",
    "INSUFFICIENT_DATA":  "Not enough information to call this",
}

# Whole phrases the engine writes for accuracy, and what a reader should see
# instead. Applied before the token-level passes because rewriting the sentence
# beats translating its parts: "walk-forward OOS positive + PBO < 0.5 + dSR ≥
# 0.5" is precise and unreadable, and no word-by-word substitution rescues it.
PHRASE_TEXT = {
    "Statistical gate clears (walk-forward OOS positive + PBO < 0.5 + "
    "net-of-cost positive + dSR ≥ 0.5 + sample ≥ 504 bars)":
        "The strategy passes its out-of-sample historical tests",
    "Live calibration reaches a readable sample":
        "This system accumulates enough of its own track record to be measured",
    "The statistical picture deteriorates further "
    "(walk-forward mean OOS Sharpe turns negative)":
        "The strategy stops working on out-of-sample history",
    "The statistical gate clears (sizing stops being 0%)":
        "The strategy passes its historical tests, so a position size becomes justified",
}

# Technical acronyms a general reader will not know. Trader-standard ones
# (ATR, RSI, MACD) are deliberately absent — they belong in this app's
# vocabulary and translating them would be condescending.
ACRONYM_TEXT = {
    "dSR": "the luck-adjusted Sharpe ratio",
    "PBO": "the overfitting probability",
    "OOS": "out-of-sample",
    "ECE": "the calibration error",
    "MAE": "the worst drawdown during the trade",
    "MFE": "the best gain during the trade",
}
_ACRONYM = re.compile(r"\b(" + "|".join(ACRONYM_TEXT) + r")\b")

_SNAKE = re.compile(r"\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b")
_CITATION = re.compile(r"\[[a-z_]+\.[a-z_.]+\]")
_IDENTIFIER = re.compile(r"\b[a-z_]+:[a-z_0-9:.-]+\b")


def plain_source(source: str) -> str:
    """One evidence source, in words."""
    if source in SOURCE_TEXT:
        return SOURCE_TEXT[source]
    if source.startswith("relative_strength:"):
        return f"how it has performed against the S&P 500 over {source.split(':', 1)[1]}"
    if source.startswith("forecast:"):
        return f"the model's {source.split(':', 1)[1]} directional read"
    if source.startswith("catalyst:"):
        return "the upcoming scheduled event"
    if source.startswith("backtest:"):
        return "the historical backtest on this stock"
    if source.startswith("pillar:"):
        return f"the {source.split(':', 1)[1]} reading"
    return source.replace("_", " ").replace(":", " ")


def plain_price(value: Optional[float]) -> str:
    return "—" if value is None else f"${value:,.2f}"


def _pct(value: Optional[float]) -> str:
    if value is None:
        return "—"
    return f"{value:+.1f}%"


def plain_call(decision: Dict[str, Any]) -> Dict[str, Any]:
    """The headline, in one line, with the ownership question answered both
    ways because the reader may be in either position."""
    ds = decision.get("decision_state") or {}
    owned = (ds.get("if_owned") or {}).get("state")
    not_owned = (ds.get("if_not_owned") or {}).get("state")
    owns = ds.get("ownership") == "OWNED"

    headline = STATE_TEXT.get(ds.get("headline_state"), ds.get("headline_state", ""))
    return {
        "headline": headline,
        "if_you_own_it": STATE_TEXT.get(owned, owned or ""),
        "if_you_dont": STATE_TEXT.get(not_owned, not_owned or ""),
        "ownership_known": owns,
        "ownership_note": (
            "You told us your entry price, so the advice above assumes you hold this."
            if owns else
            "You haven't told us whether you own this, so both answers are shown. "
            "Enter your average cost above and the advice becomes specific to you."),
    }


def plain_why(decision: Dict[str, Any], max_points: int = 3) -> List[str]:
    """Why the call is what it is — the strongest evidence, in words, no
    weights and no source identifiers."""
    evidence = decision.get("evidence") or []
    directional = [e for e in evidence if e.get("direction") in ("BULLISH", "BEARISH")]
    directional.sort(key=lambda e: e.get("weight") or 0, reverse=True)

    out: List[str] = []
    for e in directional[:max_points]:
        # Subject first, then a verbless verdict. Sources are a mix of singular
        # and plural phrases ("analyst consensus" vs "the momentum models"), so
        # any construction with a verb gets the agreement wrong half the time.
        way = "in favour" if e["direction"] == "BULLISH" else "against"
        strength = "strongly" if (e.get("weight") or 0) >= 0.6 else "mildly"
        out.append(f"{plain_source(e['source']).capitalize()} — {strength} {way}.")

    edge = decision.get("statistical_edge") or {}
    if not edge.get("demonstrated"):
        out.append(
            "But the system has not shown that acting on readings like this beats simply "
            "holding the stock, so none of this justifies a large position.")
    return out


def plain_scenarios(decision: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Bull, base and bear — one sentence and one price area each."""
    out: List[Dict[str, Any]] = []
    wanted = {"BULL": "If it goes well", "BASE": "If nothing much happens",
              "BEAR": "If it goes badly"}
    for s in (decision.get("scenarios") or {}).get("scenarios", []):
        if s.get("name") not in wanted:
            continue
        levels = s.get("price_levels") or []
        area = None
        if levels:
            prices = sorted(l["price"] for l in levels if l.get("price") is not None)
            if prices:
                area = (f"around {plain_price(prices[0])}" if len(prices) == 1
                        else f"between {plain_price(prices[0])} and {plain_price(prices[-1])}")

        conditions = [c for c in (s.get("conditions") or []) if c]
        out.append({
            "name": s["name"],
            "label": wanted[s["name"]],
            "what_happens": _strip_jargon(s.get("thesis", "")),
            "price_area": area,
            "what_would_cause_it": _strip_jargon(conditions[0]) if conditions else None,
            "how_you_would_know": _strip_jargon(s.get("invalidation", "")),
            "probability_text": (
                f"{s['probability']:.0%} chance" if s.get("probability") is not None
                else "No reliable probability — this system has not measured itself enough "
                     "to put a number on it"),
        })
    return out


def plain_triggers(decision: Dict[str, Any], max_each: int = 3) -> Dict[str, List[str]]:
    mc = decision.get("mind_changers") or {}

    def _clean(rows):
        seen, out = set(), []
        for r in rows[:max_each * 2]:
            t = _strip_jargon(r.get("trigger", ""))
            if t:
                t = t[0].upper() + t[1:]
            if t and t not in seen:
                seen.add(t)
                out.append(t)
            if len(out) == max_each:
                break
        return out

    return {"would_confirm_it": _clean(mc.get("confirmation") or []),
            "would_change_our_mind": _clean(mc.get("invalidation") or [])}


def plain_honesty(decision: Dict[str, Any]) -> str:
    """The one line that must stay visible however much else is collapsed."""
    edge = decision.get("statistical_edge") or {}
    cal = (edge.get("calibration") or {})
    if edge.get("demonstrated"):
        base = "This strategy has cleared the historical tests."
    else:
        base = ("This system has not proven it beats simply holding the stock, so treat "
                "everything here as research rather than a tested edge.")
    if cal.get("status") != "OK":
        base += " It also has no measured track record yet, so its confidence is asserted, not earned."
    return base


def plain_watch_for(decision: Dict[str, Any]) -> Optional[str]:
    cat = decision.get("catalysts") or {}
    nxt = cat.get("next_event")
    if not nxt:
        return None
    return (f"{nxt['event']} on {nxt['date']}, {nxt['days_away']} days away. That is the next "
            f"scheduled thing that can move this materially.")


def _strip_jargon(text: str) -> str:
    """Translate any leaked internal token in a sentence the engine already
    wrote, rather than rewriting the sentence.

    Applied to prose that comes from other modules (scenario theses, triggers),
    which are written for accuracy first. The readability test asserts nothing
    survives this.
    """
    if not text:
        return ""
    out = text
    for phrase, replacement in PHRASE_TEXT.items():
        out = out.replace(phrase, replacement)
    out = _ACRONYM.sub(lambda m: ACRONYM_TEXT[m.group(1)], out)
    for token, replacement in SOURCE_TEXT.items():
        out = out.replace(token, replacement)
    out = _CITATION.sub("", out)
    out = re.sub(r"\bTRADED_PRICE\b", "a price it has actually traded at", out)
    out = re.sub(r"\bPRICE_HISTORY_DERIVED\b", "a line calculated from past prices", out)
    out = re.sub(r"\bCURRENT_PRICE_DERIVED\b", "a distance from today's price", out)
    out = re.sub(r"\bMODEL\b", "a model estimate", out)
    out = re.sub(r"\bNO_DEMONSTRATED_EDGE\b",
                 "no proven advantage over simply holding", out)
    out = re.sub(r"\bINSUFFICIENT_SAMPLE\b", "not enough history to judge", out)
    out = re.sub(r"\bNOT_CALIBRATED\b", "not measured", out)
    out = _SNAKE.sub(lambda m: m.group(0).replace("_", " ").lower(), out)
    out = _IDENTIFIER.sub(lambda m: plain_source(m.group(0)), out)
    return re.sub(r"\s{2,}", " ", out).strip()


def has_jargon(text: str) -> List[str]:
    """The readability check, exposed so tests and callers use the same rule."""
    if not text:
        return []
    found = []
    found += _SNAKE.findall(text)
    found += _CITATION.findall(text)
    found += [m for m in _IDENTIFIER.findall(text) if m not in ("e.g", "i.e")]
    found += _ACRONYM.findall(text)
    return sorted(set(found))


def build_plain_summary(decision: Dict[str, Any]) -> Dict[str, Any]:
    """Everything the default view needs, in words, with no jargon surviving."""
    if decision.get("status") != "OK":
        return {
            "available": False,
            "headline": "Not enough information to make a call on this one.",
            "why": [(decision.get("decision_state") or {}).get("headline_reason", "")],
        }

    call = plain_call(decision)
    summary = {
        "available": True,
        "ticker": decision.get("ticker"),
        "price": plain_price(decision.get("current_price")),
        "call": call,
        "why": plain_why(decision),
        "scenarios": plain_scenarios(decision),
        "triggers": plain_triggers(decision),
        "honesty": plain_honesty(decision),
        "watch_for": plain_watch_for(decision),
        "how_much": (decision.get("sizing") or {}).get("statement"),
    }

    # Belt and braces: whatever assembled these strings, nothing internal
    # escapes to the reader.
    for key in ("why",):
        summary[key] = [_strip_jargon(s) for s in summary[key]]
    summary["honesty"] = _strip_jargon(summary["honesty"])
    for sc in summary["scenarios"]:
        for k in ("what_happens", "what_would_cause_it", "how_you_would_know"):
            sc[k] = _strip_jargon(sc[k] or "")
    for k in ("would_confirm_it", "would_change_our_mind"):
        summary["triggers"][k] = [_strip_jargon(s) for s in summary["triggers"][k]]
    return summary
